controller_list:
  - name: fake_endeffector_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_Arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
initial:  # Define initial robot poses.
  - group: Arm
    pose: home